### ISSUE TITLE
Please update to 1.18.2

### ISSUE THREAD

**Issue by M1noa** [MoonflowerTeam/pollen#20]
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
I cant use the mod on 1.18.2 fabric, do you have a 1.18.2 version that I cant find or something?


Image: https://imgur.com/a/EubZXQa
```

### latest.log

```shell
[18:04:45] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[18:04:46] [main/WARN]: Mod resolution failed
[18:04:46] [main/INFO]: Immediate reason: [HARD_DEP animation_overhaul 1.0.0-beta3-config {depends pollen @ [1.x]}, HARD_DEP_INCOMPATIBLE_PRESELECTED pollen 1.3.1 {depends minecraft @ [1.18.x <1.18.2]}, ROOT_FORCELOAD_SINGLE animation_overhaul 1.0.0-beta3-config]
[18:04:46] [main/INFO]: Reason: [HARD_DEP pollen 1.3.1 {depends minecraft @ [1.18.x <1.18.2]}]
[18:04:46] [main/INFO]: Fix: add [], remove [], replace [[pollen 1.3.1] -> add:pollen 1- ([[1-,2-)])]
[18:04:46] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Pollen' (pollen) 1.3.1 with any 1.x version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Pollen' (pollen) 1.3.1 requires any version between 1.18- (inclusive) and 1.18.2 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) [rust-extension-1.0.7.jar:?]
```

**Comment by jacksonhardaway** [comment]
There is no 1.18.2 version yet, we're working on it
