### ISSUE TITLE
Fatal crash when loading world on Forge

### ISSUE THREAD

**Issue by ebo2022** [MoonflowerTeam/pollen#31]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Title
```

### latest.log

```shell
[19:26:09] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgeclientuserdev, --version, MOD_DEV, --assetIndex, 1.18.2-1.18, --assetsDir, C:\Users\Ethan\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 40.1.2, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, -mixin.config, bayou_blues-common.mixins.json, -mixin.config, bayou_blues.mixins.json, --mixin.config, /bayou_blues-common.mixins.json]
[19:26:09] [main/INFO] (Launcher) ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Eclipse Adoptium
[19:26:09] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Ethan/.gradle/caches/transforms-3/8601dadbb90caf180ef06be7d296ccc0/transformed/mixin-patched-0.8.5.5.jar-alfd-transformed.jar%2317!/ Service=ModLauncher Env=CLIENT
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file javafmllanguage-1.18.2-40.1.2.jar-alfd-transformed.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4221663d
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file mclanguage-1.18.2-40.1.2.jar-alfd-transformed.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4221663d
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file fmlcore-1.18.2-40.1.2.jar-alfd-transformed.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4221663d
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4221663d
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file main of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4221663d
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file  of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4221663d
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file B18661e5a74c4-B18661e5a74c4.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file Bca649d0d0d93-Bca649d0d0d93.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file Bb7d4f7f04268-Bb7d4f7f04268.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file 16697234666590793109.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file B18661e5a74c4-B18661e5a74c4.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file Bca649d0d0d93-Bca649d0d0d93.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file Bb7d4f7f04268-Bb7d4f7f04268.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:09] [main/INFO] (ModDiscoverer) Found mod file 16697234666590793109.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@7e544223
[19:26:12] [main/INFO] (mixin) Compatibility level set to JAVA_17
[19:26:12] [main/INFO] (LaunchServiceHandler) Launching target 'forgeclientuserdev' with arguments [--version, MOD_DEV, --gameDir, ., --assetsDir, C:\Users\Ethan\.gradle\caches\fabric-loom\assets, --assetIndex, 1.18.2-1.18]
[19:26:12] [main/INFO] (mixin) Remapping refMap pollen-common-refmap.json using RemapperChain (Architectury Patched)
[19:26:12] [main/INFO] (mixin) Remapping refMap pollen-refmap.json using RemapperChain (Architectury Patched)
[19:26:17] [Render thread/WARN] (Minecraft) Assets URL 'union:/C:/Users/Ethan/Desktop/modding/BayouBlues/.gradle/loom-cache/1.18.2/loom.mappings.1_18_2.layered+hash.40353-v2-forge-1.18.2-40.1.2/forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/assets/.mcassetsroot' uses unexpected schema
[19:26:17] [Render thread/WARN] (Minecraft) Assets URL 'union:/C:/Users/Ethan/Desktop/modding/BayouBlues/.gradle/loom-cache/1.18.2/loom.mappings.1_18_2.layered+hash.40353-v2-forge-1.18.2-40.1.2/forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/data/.mcassetsroot' uses unexpected schema
[19:26:17] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:26:17] [Render thread/INFO] (Minecraft) Setting user: Dev
[19:26:17] [Render thread/INFO] (Minecraft) Backend library: LWJGL version 3.2.2 SNAPSHOT
[19:26:19] [modloading-worker-0/INFO] (ForgeMod) Forge mod loading, version 40.1.2, for MC 1.18.2 with MCP 20220404.173914
[19:26:19] [modloading-worker-0/INFO] (MinecraftForge) MinecraftForge v40.1.2 Initialized
[19:26:24] [Render thread/INFO] (Minecraft) Narrator library for x64 successfully loaded
[19:26:24] [Render thread/INFO] (ForgeGameTestHooks) Enabled Gametest Namespaces: []
[19:26:24] [Render thread/INFO] (Minecraft) Reloading ResourceManager: Default, Mod Resources
[19:26:24] [modloading-worker-0/WARN] (ForgeConfigSpec) Configuration file C:\Users\Ethan\Desktop\modding\BayouBlues\forge\run\config\configured_test_config.toml is not correct. Correcting
[19:26:24] [modloading-worker-0/WARN] (ForgeConfigSpec) Incorrect key lists.longList was corrected from [5, 10] to its default, [5, 10]. 
[19:26:25] [Worker-Main-20/INFO] (LocalTextureTableLoader) Loaded 0 hash tables.
[19:26:25] [Worker-Main-22/INFO] (LocalTextureTableLoader) Loaded 0 model texture tables.
[19:26:25] [Worker-Main-19/INFO] (LocalGeometryModelLoader) Loaded 0 geometry models.
[19:26:25] [Worker-Main-22/INFO] (LocalGeometryModelLoader) Loaded 0 geometry models.
[19:26:25] [Forge Version Check/INFO] (VersionChecker) [configured] Starting version check at https://mrcrayfish.com/modupdatejson?id=configured
[19:26:26] [Forge Version Check/INFO] (VersionChecker) [configured] Found status: BETA_OUTDATED Current: 1.5.1 Target: 1.5.3
[19:26:26] [Forge Version Check/INFO] (VersionChecker) [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[19:26:26] [Forge Version Check/INFO] (VersionChecker) [forge] Found status: OUTDATED Current: 40.1.2 Target: 40.1.14
[19:26:26] [Forge Version Check/INFO] (VersionChecker) [catalogue] Starting version check at https://mrcrayfish.com/modupdatejson?id=catalogue
[19:26:26] [Forge Version Check/INFO] (VersionChecker) [catalogue] Found status: BETA_OUTDATED Current: 1.6.0 Target: 1.6.1
[19:26:31] [Worker-Main-18/INFO] (configured) Creating config GUI factories...
[19:26:31] [Worker-Main-18/INFO] (configured) Registering config factory for mod configured. Found 2 client config(s) and 0 common config(s)
[19:26:31] [Worker-Main-18/INFO] (configured) Registering config factory for mod forge. Found 1 client config(s) and 1 common config(s)
[19:26:33] [Render thread/INFO] (Minecraft) OpenAL initialized on device OpenAL Soft on Headset Earphone (Corsair HS60 PRO Surround USB Sound Adapter)
[19:26:33] [Render thread/INFO] (Minecraft) Sound engine started
[19:26:33] [Render thread/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[19:26:33] [Render thread/INFO] (Minecraft) Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:26:33] [Render thread/INFO] (Minecraft) Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:26:33] [Render thread/INFO] (Minecraft) Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:26:33] [Render thread/INFO] (Minecraft) Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:26:33] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:26:33] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:26:34] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:26:34] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:26:34] [Render thread/INFO] (Minecraft) Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:26:34] [Render thread/INFO] (Minecraft) Created: 16x16x4 pollen:textures/atlas/geometry.png-atlas
[19:26:34] [Render thread/INFO] (AnimationManager) Loaded 0 animations.
[19:26:34] [Render thread/INFO] (GeometryModelManager) Loaded 0 geometry models.
[19:26:35] [Realms Notification Availability checker #1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id
[19:27:17] [Render thread/ERROR] (ForgeHooks) This world was saved with mod generated_6efec3f which appears to be missing, things may not work well
[19:27:17] [Render thread/INFO] (GameData) Injecting existing registry data into this CLIENT instance
[19:27:18] [Render thread/WARN] (Minecraft) Missing data pack mod:generated_6efec3f
[19:27:18] [Render thread/WARN] (Minecraft) Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:27:18] [Render thread/WARN] (Minecraft) Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:27:18] [Render thread/WARN] (Minecraft) Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:27:18] [Render thread/WARN] (Minecraft) Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:27:18] [Render thread/WARN] (Minecraft) Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:27:19] [Render thread/INFO] (Minecraft) Loaded 7 recipes
[19:27:20] [Render thread/INFO] (Minecraft) Loaded 1141 advancements
[19:27:21] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:27:21] [Server thread/INFO] (Minecraft) Starting integrated minecraft server version 1.18.2
[19:27:21] [Server thread/INFO] (Minecraft) Generating keypair
[19:27:21] [Server thread/INFO] (Minecraft) Preparing start region for dimension minecraft:overworld
[19:27:21] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[19:27:21] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[19:27:22] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[19:27:22] [Render thread/INFO] (Minecraft) Preparing spawn area: 4%
[19:27:23] [Render thread/INFO] (Minecraft) Preparing spawn area: 77%
[19:27:23] [Server thread/INFO] (PermissionAPI) Successfully initialized permission handler forge:default_handler
[19:27:23] [Render thread/INFO] (Minecraft) Time elapsed: 2414 ms
[19:27:23] [Server thread/INFO] (Minecraft) Changing view distance to 12, from 10
[19:27:23] [Server thread/INFO] (Minecraft) Changing simulation distance to 12, from 0
[19:27:24] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:906) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:842) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:84) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:685) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList$Builder com.google.common.collect.ImmutableList.builderWithExpectedSize(int)'
	at net.minecraft.world.entity.Entity.collideBoundingBox(Entity.java:818) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.Entity.collide(Entity.java:794) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.Entity.move(Entity.java:579) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2155) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2112) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.animal.Pig.travelWithInput(Pig.java:234) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.ItemSteerable.travel(ItemSteerable.java:25) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.animal.Pig.travel(Pig.java:226) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2544) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:495) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:127) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:54) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2253) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:307) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:652) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:486) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$3(ServerLevel.java:319) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:299) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:902) ~[forge-1.18.2-40.1.2-minecraft-project-@forge-mapped.jar%2365!/:?]
	... 5 more
[19:27:24] [Server thread/FATAL] (ForgeMod) Preparing crash report with UUID d1cebda5-c2ac-4a00-ae8f-cbaa2fdbb1bb
[19:27:24] [Server thread/ERROR] (Minecraft) This crash report has been saved to: C:\Users\Ethan\Desktop\modding\BayouBlues\forge\run\.\crash-reports\crash-2022-05-03_19.27.24-server.txt
[19:27:24] [Server thread/INFO] (Minecraft) Stopping server
[19:27:24] [Server thread/INFO] (Minecraft) Saving players
[19:27:24] [Server thread/INFO] (Minecraft) Saving worlds
[19:27:24] [Render thread/FATAL] (ForgeMod) Preparing crash report with UUID 2a1e9039-87f1-459e-8517-85711b9dc480
```

**Comment by jacksonhardaway** [comment]
This does not seem to be an issue with Pollen

**Comment by ebo2022** [comment]
Will reopen if I find anything relevant
