### ISSUE TITLE
[BUG] Minecraft world creation going to safety mode.

### ISSUE THREAD

**Issue by KKotik** [MoonflowerTeam/pollen#4]
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
The title explains itself. Happening on Forge 1.18.
```

### latest.log

```shell
[17:59:13] [Render thread/ERROR]: Error adding element: Unknown registry element in ResourceKey[minecraft:root / minecraft:worldgen/feature]:teamdraco.bettas.feature.MossBallFeature@3e4dccb1
[17:59:18] [Render thread/INFO]: Adding global data pack provider...
[17:59:18] [Render thread/INFO]: Found new data pack Repurposed_Structures-Farmers_Delight_v3.zip, loading it automatically
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [ftbteams, info, server_id] and [ftbteams, info, team] with inputs: [server_id]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [create, coupling, add, cart1] and [create, coupling, add, carts] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [create, coupling, add, carts] and [create, coupling, add, cart1] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [create, coupling, add, cart1] and [create, coupling, add, carts] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [create, coupling, add, carts] and [create, coupling, add, cart1] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:59:18] [Render thread/WARN]: Ambiguity between arguments [jph, cache] and [jph, name] with inputs: [cache]
[17:59:18] [Render thread/ERROR]: Failed to get RegistryReadOps for the ChunkGeneratorModificationManager for an unknown RegistryAccess: net.minecraft.core.RegistryAccess$RegistryHolder@928c53b
[17:59:18] [Render thread/ERROR]: Failed to get RegistryReadOps for the BiomeSourceModificationManager for an unknown RegistryAccess: net.minecraft.core.RegistryAccess$RegistryHolder@928c53b
[17:59:18] [Render thread/INFO]: Hello, World! (You will see this line every time server resources reload)
[17:59:18] [Render thread/INFO]: Loaded script server_scripts:script.js in 0.005 s
[17:59:18] [Render thread/INFO]: Loaded 1/1 KubeJS server scripts in 0.009 s
[17:59:18] [Render thread/INFO]: Scripts loaded
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type kubejs:shaped
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type kubejs:shapeless
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:crafting_shaped
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:crafting_shapeless
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:stonecutting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:smelting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:blasting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:smoking
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:campfire_cooking
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type minecraft:smithing
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:sequenced_assembly
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:mechanical_crafting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:conversion
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:crushing
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:cutting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:milling
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:basin
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:mixing
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:compacting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:pressing
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:sandpaper_polishing
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:splashing
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:haunting
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:deploying
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:filling
[17:59:18] [Render thread/INFO]: Registered custom recipe handler for type create:emptying
[17:59:18] [Render thread/INFO]: Scanning recipes...
[17:59:18] [Render thread/INFO]: Reloading ResourceManager: KubeJS Virtual Data Pack [low priority], Default, habitat-1.1.2.jar, BetterDungeons-Forge-1.18.1-0.1.1.jar, GlobalGameRules-1.18.1-6.0.0.5.jar, bigbrain-1.4.1.jar, locksmith-forge-1.0.0+1.18.1.jar, windowlogging-mc1.18.1_v0.0.8.jar, rubidium-0.5.0.jar, hourglass-1.18-1.2.1.0.jar, advancementframes-1.18-1.0.5.jar, YungsApi-1.18.1-Forge-24.jar, skeletonhorsespawn_1.18.1-2.0.jar, clickadv-1.18.1-2.3.jar, PickUpNotifier-v3.1.0-1.18.1-Forge.jar, nicephore-1.18.x-1.2.1.jar, zombievillagersfromspawner_1.18.1-1.7.jar, balm-2.4.2+0.jar, SnowRealMagic-1.18.1-forge-3.2.5.jar, dynview-1.18.1-2.4.jar, JustEnoughResources-1.18.1-0.13.2.153.jar, chat_heads-0.6.0-forge-1.18.1.jar, Paraglider-1.18-1.5.0.0.jar, cloth-config-6.2.57-forge.jar, stackrefill_1.18.1-2.1.jar, hoetweaks_1.18.1-1.3.jar, refinedstorage-1.10.0.jar, structure_gel-1.18.1-2.1.3.jar, AdvancementPlaques-1.18.1-1.4.2.jar, TinySkeletons-v3.1.0-1.18.1-Forge.jar, cleancut-mc1.18-3.0-forge.jar, repurposed_structures_forge-4.2.11+1.18.1.jar, BetterCompatibilityChecker-1.1.12-build.24+mc1.18.1.jar, BiomesOPlenty-1.18.1-15.0.0.104-universal.jar, verdure-1.18.1-1.0.4.jar, jepp-1.18-1.0.0.jar, ImprovedMountHUD-v3.0.1-1.18.1-Forge.jar, pop-1.18-1.0.0.jar, YungsBridges-Forge-1.18.1-0.1.0.jar, Highlighter-1.18.1-1.1.2.jar, curios-forge-1.18.1-5.0.6.1.jar, YungsExtras-Forge-1.18.1-0.2.0.jar, antighost-1.18.1-forge39.0.9-1.1.2.jar, sapience-1.18.1-1.0.2.jar, furniture-7.0.0-pre28-1.18.1.jar, krypton-1.0.0.jar, bettas-1.18-1.0.0.jar, BetterMineshafts-Forge-1.18.1-0.1.0.jar, geckolib-1.18-forge-3.0.10.jar, BetterModsButton-v3.1.0-1.18.1-Forge.jar, DripSounds-1.18-0.3.0.jar, radium-0.7.7g.jar, QuarkOddities-1.18.jar, Kiwi-1.18-forge-5.2.5.jar, StylishEffects-v3.0.2-1.18.1-Forge.jar, shieldmechanics-1.18-2.9.jar, panda_genetics_tweak-1.18.X-1.0.jar, jei-1.18.1-9.4.1.103.jar, VisualWorkbench-v3.1.0-1.18.1-Forge.jar, AttributeFix-Forge-1.18.1-13.0.5.jar, goblintraders-1.7.0-1.18.1.jar, caelus-forge-1.18.1-3.0.0.2.jar, Paxi-Forge-1.18.1-1.0.jar, Fallingleaves-1.18.1-1.3.1.jar, smarterfarmers-1.18-1.2.1.jar, SereneSeasons-1.18.1-6.0.0.11-universal.jar, snowundertrees-1.18.1-1.2.jar, snuffles-1.0.1.jar, starlight-1.0.1+forge.36a1c6c.jar, BeeFix-1.18-1.0.0.3.jar, questsadditions-1.18-1.0.0.jar, catalogue-1.6.0-1.18.1.jar, dismountentity_1.18.1-1.6.jar, chalk-1.18.1-1.2.0.jar, logprot-1.18-1.4.jar, voicechat-forge-1.18.1-2.2.22.jar, soundphysics-forge-1.18.1-1.0.4.jar, TerraBlender-forge-1.18.1-1.1.0.77.jar, physics-mod-2.6.7-mc-1.18-forge.jar, MouseTweaks-forge-mc1.18-2.21.jar, Companion-1.18-forge-1.2.0.jar, screenshotcopy-1.0.0-forge.jar, inventorytotem_1.18.1-1.6.jar, betterfpsdist-1.18-1.3.jar, mmlib-1.0.0-1.18.1.jar, notenoughanimations-forge-1.4.0-mc1.18.jar, flywheel-forge-1.18-0.6.0.jar, alloyed-1.18.1-v1.2.jar, Mantle-1.18.1-1.8.31.jar, ecologics-FORGE-1.18.1-1.2.1.jar, NotEnoughBreeding-1.18.1-1.0.0.jar, cyclepaintings_1.18.1-2.2.jar, AutoRegLib-1.7-52.jar, entityculling-forge-mc1.18-1.5.0.jar, backpacked-2.0.4-1.18.1.jar, effective_for_forge-1.001.jar, AmbientEnvironment-forge-1.18.1-7.0+17.jar, FastFurnace-1.18.1-6.0.2.jar, visuality-0.4.0-1.18-forge.jar, ForgeCustomCursorMod-1.3.0.jar, ModernUI-1.18.1-3.3.0.98-universal.jar, DamageTilt-1.18-forge-0.1.1.jar, PuzzlesLib-v3.1.5-1.18.1-Forge.jar, mannequins-forge-2.0.0+1.18.1.jar, responsiveshields-1.1-mc1.18.x.jar, OptifineCapes-1.18.x-1.0.jar, notenoughcrashes-4.1.4+1.18.1-forge.jar, no_null_processors_forge-2.0.2+1.18.1.jar, hitchhike-1.1.jar, netherportalfix-forge-1.18-9.0.0.jar, zombiehorsespawn_1.18.1-3.1.jar, fish_in_planks-1.18.1-0.5.jar, SuggestionProviderFix-1.18.1-1.0.0.jar, HealthOverlay-1.18.1-6.0.0.jar, Architects-Palette-1.18.1-1.1.3.jar, incontrol-1.18-6.0.0.jar, InsaneLib-1.4.3-mc1.18.1.jar, chatcolours-1.18-1.0.jar, Cave_Tweaks_v1.2_Forge.jar, paperdoll-forge-1.0.0-mc1.18.jar, Controlling-forge-1.18.1-9.0+15.jar, Placebo-1.18.1-6.1.1.jar, citadel-1.10.10-1.18.jar, alexsmobs-1.17.1.jar, Tab-Stats-1.18-1.0.1.jar, moreminecarts-1.4.3.jar, feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.jar, itemzoom-1.18.1-2.5.0.jar, PatinaPipeworks-1.18.1-1.0.6-universal.jar, twigs-1.1.4-forge.jar, jeed-1.18.1-1.7.jar, keepmysoiltilled_1.18.1-1.1.jar, hedgehog-1.1.2.jar, omnis-1.18.1-1.2.jar, hauntedharvest-1.18-1.7.1.jar, winteroverhaul-1.0.0.jar, ExperienceBugFix-1.18-1.38.0.2.jar, EquipmentCompare-1.18.1-1.2.12.jar, FarmersDelight-1.18.1-1.0.3.jar, corn_delight-1.0.4-1.18.1.jar, customizableelytra-1.18-1.6.3.jar, DustrialDecor-1.3.1-1.18.jar, curious-armor-stands-1.18.1-4.0.0.jar, Decorative+Blocks+Compat-forge-1.18.1-2.0.0.jar, musicdr-1.4.0.jar, RapidLeafDecay-1.18.1-2.0.0.jar, moyai-1.18-1.1.2.jar, LetSleepingDogsLie-1.18-1.1.1.jar, Boat-Item-View-Forge-1.18-0.0.3.jar, skinned_lanterns-1.18.1-1.3.2.jar, naturallychargedcreepers_1.18.1-1.8.jar, collective-1.18.1-4.7.jar, cakechomps-forge-1.18-5.1.0.0.jar, BetterStrongholds-Forge-1.18.1-1.0.2.jar, architectury-3.7.22.jar, ftb-library-forge-1801.3.5-build.109.jar, ftb-teams-forge-1801.2.4-build.46.jar, curiouselytra-forge-1.18.1-5.0.1.0.jar, AI-Improvements-1.18-0.4.0.jar, enchantwithmob-1.18.1-3.3.0.jar, cursery-1.18.1-2.8.jar, anchor-forge-1.0.0+1.18.1.jar, BetterAdvancements-1.18.1-0.1.2.122.jar, [1.18.1]Paused-1.1.0.jar, rhino-forge-1801.1.8-build.102.jar, kubejs-forge-1801.4.2-build.300.jar, kubejs-ui-forge-1801.1.6-build.11.jar, mosaic_blocks-1.18.1-1.0.jar, item-filters-forge-1801.2.6-build.16.jar, ftb-quests-forge-1801.3.7-build.93.jar, EasyMagic-v3.2.1-1.18.1-Forge.jar, the-conjurer-1.18.1-1.1.1.jar, ponderjs-1.18.1-1.0.4a.jar, create-mc1.18.1_v0.4d.jar, kubejs-create-1801.2.0-build.14.jar, JER-Integration-2.2.0-experimental.jar, waystones-forge-1.18.1-9.0.3.jar, MerchantMarkers-1.18.1-1.1.3.jar, goldenhopper-1.2.6-1.18.1.jar, mcw-paintings-1.0.2-mc1.18.1.jar, FastSuite-1.18.1-3.0.0.jar, Clumps-forge-1.18.1-8.0.0+5.jar, artifacts-1.18.1-4.0.2.jar, alternate-current-mc1.18-1.1.0.jar, configured-1.5.3-1.18.1.jar, ItemBorders-1.18.1-1.1.5.jar, Decorative+Blocks-forge-1.18.1-2.0.4.jar, DungeonCrawl-1.18.1-2.3.7.jar, Nimble-1.18-forge-2.2.0.jar, lazydfu-1.0-1.18+.jar, Mc122477Fix-mc1.18.jar, farsight-1.18-1.6.jar, blueprint-1.18.1-5.1.1.jar, boatload-1.18.1-3.0.0.jar, savage_and_ravage-1.18.1-4.0.0.jar, neapolitan-1.18.1-3.0.0.jar, personality-1.18.1-2.0.0.jar, allurement-1.18.1-2.0.0.jar, Compat-O-Plenty-1.18.1-1.4.1.jar, incubation-1.18.1-2.0.0.jar, berry_good-1.18.1-5.0.0.jar, BetterTaskbar-1.18-Forge-1.2.jar, 3dSkinLayers-forge-mc1.18-1.4.1.jar, TravelersTitles-Forge-1.18.1-0.1.1.jar, morezombievillagers_1.18.1-1.6.jar, selene-1.18-1.13.1.jar, supplementaries-1.18.1-1.2.1.jar, craftingtweaks-forge-1.18.1-14.0.2.jar, illagersweararmor-1.1.0.jar, TConstruct-1.18.1-3.4.1.46.jar, EnchantmentDescriptions-Forge-1.18.1-9.0.13.jar, swingthroughgrass-1.18.1-1.8.0.jar, pollen-forge-1.0.0+1.18.1.jar, ToolBelt-1.18-1.18.0.jar, titanium-1.18-3.4.0-27.jar, icepreventscropgrowth_1.18.1-1.5.jar, Jade-1.18-4.2.0.jar, forge-1.18.1-39.0.79-universal.jar, appleskin-forge-mc1.18-2.3.0.jar, cyanide-forge-1.18-2.0.3.jar, snowyspirit-1.18-1.1.0.jar, whats-that-slot-forge-1.2.3+1.18.1.jar, IguanaTweaksReborn-2.9.2-mc1.18.1.jar, justplayerheads_1.18.1-1.9.jar, Iceberg-1.18.1-1.0.40.jar, Quark-3.1-339.jar, DramaticDoors-1.18.1-1.5.1.jar, LegendaryTooltips-1.18.1-1.2.4.jar, VariantCraftingTables-1.18.1-1.4.jar, diet-forge-1.18.1-1.2.0.4.jar, malum-1.18.1-1.2.2.jar, FastWorkbench-1.18.1-6.0.1.jar, abnormals_delight-1.18.1-2.0.0.jar, Seed+Drop-1.18-2.1.3.jar, Alex's+Delights+1.2.0.jar, ferritecore-4.1.2-forge.jar, SoL-Carrot-1.18.1-1.12.0.jar, functionalstorage-1.18.1-0.0.10.jar, NoChatLagForge-1.1.0.jar, enhancedcelestials-2.0.9-1.18.jar, BetterF3-1.2.2-Forge-1.18.jar, ArmorSoundTweak-5.0.0-forge.jar, expandability-5.0.0-forge.jar, Repurposed_Structures-Farmers_Delight_v3.zip, KubeJS Resource Pack [data], KubeJS Virtual Data Pack [high priority]
[17:59:19] [Render thread/ERROR]: Parsing error loading custom data modifier anchor:creeper_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[17:59:19] [Render thread/ERROR]: Parsing error loading custom data modifier anchor:end_city_treasure_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[17:59:19] [Render thread/ERROR]: Parsing error loading custom data modifier anchor:simple_dungeon_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[17:59:19] [Render thread/ERROR]: Parsing error loading custom data modifier anchor:stronghold_corridor_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[17:59:19] [Render thread/ERROR]: Parsing error loading custom data modifier anchor:nether_bridge_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[17:59:19] [Render thread/INFO]: Loaded 0 data modifiers
[17:59:19] [Worker-Main-3/INFO]: [potions] Found 0 tags, added 0 objects, removed 0 objects
[17:59:19] [Worker-Main-1/INFO]: [structure_features] Found 1 tags, added 0 objects, removed 0 objects
[17:59:19] [Worker-Main-6/INFO]: [enchantments] Found 1 tags, added 0 objects, removed 0 objects
[17:59:19] [Worker-Main-6/INFO]: [entity_types] Found 67 tags, added 0 objects, removed 0 objects
[17:59:19] [Worker-Main-6/INFO]: [block_entity_types] Found 0 tags, added 0 objects, removed 0 objects
[17:59:19] [Worker-Main-1/INFO]: [blocks] Found 502 tags, added 0 objects, removed 0 objects
[17:59:19] [Worker-Main-1/ERROR]: Couldn't load tag dramaticdoors:tall_wooden_doors as it is missing following references: dramaticdoors:tall_ba_blossom_door (from DramaticDoors-1.18.1-1.5.1.jar)
[17:59:19] [Worker-Main-1/ERROR]: Couldn't load tag dramaticdoors:tall_doors as it is missing following references: #dramaticdoors:tall_wooden_doors (from DramaticDoors-1.18.1-1.5.1.jar)
[17:59:19] [Worker-Main-3/INFO]: [items] Found 778 tags, added 0 objects, removed 0 objects
[17:59:20] [Worker-Main-6/INFO]: [fluids] Found 111 tags, added 0 objects, removed 0 objects
[17:59:20] [Worker-Main-6/ERROR]: Couldn't load tag pollen:test as it is missing following references: pollen:test (from pollen-forge-1.0.0+1.18.1.jar),pollen:flowing_test (from pollen-forge-1.0.0+1.18.1.jar)
[17:59:20] [Worker-Main-3/INFO]: [mob_effects] Found 1 tags, added 0 objects, removed 0 objects
[17:59:20] [Worker-Main-1/INFO]: [game_events] Found 2 tags, added 0 objects, removed 0 objects
[17:59:20] [Worker-Main-1/INFO]: [functions] Found 0 tags, added 0 objects, removed 0 objects
[17:59:20] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2071) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1906) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.Minecraft.handler$clk000$createLevel(Minecraft.java:9859) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.Minecraft.m_91202_(Minecraft.java) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:240) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$init$13(CreateWorldScreen.java:181) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%236!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:202) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1062) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.79.jar%2351!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%2340!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getCondition(CraftingHelper.java:232) ~[forge-1.18.1-39.0.79-universal.jar%23296!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:224) ~[forge-1.18.1-39.0.79-universal.jar%23296!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:213) ~[forge-1.18.1-39.0.79-universal.jar%23296!/:?]
	at gg.moonflower.pollen.api.registry.forge.ResourceConditionRegistryImpl.test(ResourceConditionRegistryImpl.java:48) ~[pollen-forge-1.0.0+1.18.1.jar%23232!/:?]
	at gg.moonflower.pollen.api.registry.ResourceConditionRegistry.test(ResourceConditionRegistry.java) ~[pollen-forge-1.0.0+1.18.1.jar%23232!/:?]
	at gg.moonflower.pollen.api.resource.condition.ConditionalTagEntry.m_7657_(ConditionalTagEntry.java:29) ~[pollen-forge-1.0.0+1.18.1.jar%23232!/:?]
	at net.minecraft.tags.Tag$Builder.m_144371_(Tag.java:104) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.tags.TagLoader.m_144533_(TagLoader.java:128) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.tags.TagLoader.m_144523_(TagLoader.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.tags.TagLoader.m_144509_(TagLoader.java:81) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.tags.TagLoader.m_144523_(TagLoader.java:81) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.tags.TagLoader.m_144515_(TagLoader.java:127) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.tags.TagLoader.m_144507_(TagLoader.java:127) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.tags.TagLoader.m_144544_(TagLoader.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at net.minecraft.tags.TagManager.m_144587_(TagManager.java:74) ~[client-1.18.1-20211210.034407-srg.jar%23292!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[17:59:33] [Render thread/ERROR]: Error adding element: Unknown registry element in ResourceKey[minecraft:root / minecraft:worldgen/feature]:teamdraco.bettas.feature.MossBallFeature@3e4dccb1
[17:59:36] [Render thread/INFO]: Stopping!
```

**Comment by KKotik** [comment]
![image](https://user-images.githubusercontent.com/45950781/155160683-f444cf56-6a93-4156-b685-bf71867f94ba.png)
[debug.log](https://github.com/MoonflowerTeam/pollen/files/8117739/debug.log)
[latest.log](https://github.com/MoonflowerTeam/pollen/files/8117737/latest.log)

**Comment by VirtualGaming1** [comment]
just quick question, Have you open this world and played it in the same season?
