### ISSUE TITLE
[GAMEBREAKING] Cannot load any worlds due to "errors in selected datapacks"

### ISSUE THREAD

**Issue by Tempest-5ky** [MoonflowerTeam/pollen#49]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Download Pollen for Fabric 1.18.2
2. Load minecraft
3. Try to create a world
4. Get error

Initially found issue in a modpack with ~300 mods but I tested with only Pollen and fabric API and got the same issue/error. GAMEBREAKING, completely prevents creation of worlds!
```

### latest.log

```shell
[19:10:30] [Worker-Main-11/WARN]: Failed to validate datapack
java.util.concurrent.CompletionException: java.lang.NullPointerException: Expected to wait for resource modifiers, but serverReloader was null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NullPointerException: Expected to wait for resource modifiers, but serverReloader was null
	at gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager.getServerCompleteFuture(ResourceModifierManager.java:117) ~[pollen-fabric-1.4.3+1.18.2.jar:?]
	at net.minecraft.loot.LootManager.prepare(LootManager:3529) ~[?:?]
	at net.minecraft.resource.JsonDataLoader.prepare(JsonDataLoader:21) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
```

**Comment by jacksonhardaway** [comment]
Duplicate issue
