### ISSUE TITLE
Fabric data gen not working

### ISSUE THREAD

**Issue by CoffeeCatRailway** [MoonflowerTeam/pollen#51]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
I get the same error when running any tag data gen when using pollen 1.4.1+1.18.2
```

### latest.log

```shell
[15:31:22] [Render thread/ERROR] (FabricDataGenHelper) Failed to run data generation
 java.lang.RuntimeException: Failed to run data generator from mod (plus)
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.runInternal(FabricDataGenHelper.java:133) ~[fabric-data-generation-api-v1-3.0.0+9fcb91d260.jar:?]
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.run(FabricDataGenHelper.java:97) [fabric-data-generation-api-v1-3.0.0+9fcb91d260.jar:?]
	at net.minecraft.client.Minecraft.handler$zjj000$main(Minecraft.java:3878) [minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:426) [minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:181) [minecraft-project-@fabric-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217) [architectury-transformer-5.2.66-runtime.jar:5.2.66]
Caused by: java.lang.UnsupportedOperationException
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149) ~[?:?]
	at net.minecraft.data.tags.TagsProvider.localvar$zdi000$modifyList(TagsProvider.java:1026) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.data.tags.TagsProvider.method_27046(TagsProvider.java:57) ~[minecraft-project-@fabric-merged-named.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.tags.TagsProvider.run(TagsProvider.java:51) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.data.DataGenerator.run(DataGenerator.java:42) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.runInternal(FabricDataGenHelper.java:131) ~[fabric-data-generation-api-v1-3.0.0+9fcb91d260.jar:?]
	... 13 more

Process finished with exit code -1
```

**Comment by jacksonhardaway** [comment]
Fixed in 5d8442bd2619669b49dfedc553e5b8468baa01fe
