### ISSUE TITLE
Fabric crash w/ Mixin Extras

### ISSUE THREAD

**Issue by ebo2022** [MoonflowerTeam/pollen#52]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Update pollen dependency to the latest version in IntelliJ (1.4.4 as of when I opened this issue)
2. Run fabric
3. Crash will present itself
```

### latest.log

```shell
[19:05:10] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.18.2 with Fabric Loader 0.14.4
[19:05:10] [main/INFO] (FabricLoader) Loading 52 mods:
	- bayou_blues 1.0.0
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860
	- fabric-api-lookup-api-v1 1.6.0+2373a54560
	- fabric-biome-api-v1 8.0.4+7b0f312660
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560
	- fabric-command-api-v1 1.1.9+d7c144a860
	- fabric-commands-v0 0.2.8+b4f4f6cd60
	- fabric-containers-v0 0.1.21+d7c144a860
	- fabric-content-registries-v0 3.0.3+d82b939260
	- fabric-convention-tags-v1 1.0.1+474e4f7960
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560
	- fabric-data-generation-api-v1 2.0.9+e19de87d60
	- fabric-dimensions-v1 2.1.17+2540745460
	- fabric-entity-events-v1 1.4.8+d7c144a860
	- fabric-events-interaction-v0 0.4.19+d7c144a860
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860
	- fabric-game-rule-api-v1 1.0.13+d7c144a860
	- fabric-gametest-api-v1 1.0.16+91b7aa6660
	- fabric-item-api-v1 1.4.0+4457765560
	- fabric-item-groups-v0 0.3.11+91896a4960
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60
	- fabric-loot-tables-v1 1.0.11+d7c144a860
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60
	- fabric-models-v0 0.3.6+d7c144a860
	- fabric-networking-api-v1 1.0.21+d882b91560
	- fabric-networking-v0 0.3.8+b4f4f6cd60
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060
	- fabric-particles-v1 0.2.12+526dc1ac60
	- fabric-registry-sync-v0 0.9.8+0d9ab37260
	- fabric-renderer-api-v1 0.4.13+d882b91560
	- fabric-renderer-indigo 0.5.0+7faf0d8860
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60
	- fabric-rendering-v0 1.1.13+b4f4f6cd60
	- fabric-rendering-v1 1.10.7+54e5b2ec60
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	- fabric-resource-loader-v0 0.4.18+2de5574560
	- fabric-screen-api-v1 1.0.10+d882b91560
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860
	- fabric-textures-v0 1.0.12+3ac43d9560
	- fabric-transfer-api-v1 1.6.0+2373a54560
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860
	- fabricloader 0.14.4
	- generated_9bdd5a3 1.0.0
	- java 17
	- minecraft 1.18.2
	- modmenu 3.0.1
	- pollen 1.4.4
[19:05:10] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Ethan/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/ec0cac7c741efa6be5ebd4c7fafe4240b0f6285d/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:05:10] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[19:05:10] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
[19:05:10] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[19:05:10] [main/ERROR] (FabricLoader) Uncaught exception in thread "main"
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:318) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:450) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217) ~[architectury-transformer-5.2.66-runtime.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/llamalad7/mixinextras/MixinExtrasBootstrap
	at gg.moonflower.pollen.core.PollenMixinPlugin.onLoad(PollenMixinPlugin.java:14) ~[pollen-fabric-1.4.4+1.18.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:409) ~[fabric-loader-0.14.4.jar:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: can't find class com.llamalad7.mixinextras.MixinExtrasBootstrap
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:227) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at gg.moonflower.pollen.core.PollenMixinPlugin.onLoad(PollenMixinPlugin.java:14) ~[pollen-fabric-1.4.4+1.18.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:409) ~[fabric-loader-0.14.4.jar:?]
	... 9 more
```

**Comment by jacksonhardaway** [comment]
Fixed in bbea68e5e3c8d1c5f29dc435d34ac83a9c06afd6
