### ISSUE TITLE
Client hangs on "Encrypting..." when accounts.moonflower.gg is unreachable

### ISSUE THREAD

**Issue by HatTrkPatrk** [MoonflowerTeam/pollen#65]
### What version are you seeing the problem on?

1.16.5

### Describe the issue

```markdown
When accounts.everglow.gg is unreachable by your client for whatever reason, the game is stuck on "Encrypting..." when trying to connect to a multiplayer server.

1. Wait for accounts.moonflower.gg to be unreachable for whatever reason.
2. Attempt to connect to a 1.16.5 Forge server that uses Pollen.
```

### latest.log

```shell
[05Sep2022 11:34:22.638] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: java.io.IOException: Failed to connect to 'https://accounts.moonflower.gg/api/v1/user/minecraft/a2f278b2-f07b-4cb9-add2-a32d52c6162e'. 522 
[05Sep2022 11:34:22.638] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at gg.moonflower.pollen.core.client.profile.ProfileConnection.checkError(ProfileConnection.java:127)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at gg.moonflower.pollen.core.client.profile.ProfileConnection.getProfileJson(ProfileConnection.java:138)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at gg.moonflower.pollen.core.client.profile.ProfileConnection.getProfileData(ProfileConnection.java:224)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at gg.moonflower.pollen.core.client.profile.ProfileManager.lambda$getProfile$0(ProfileManager.java:34)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at gg.moonflower.pollen.core.client.profile.ProfileManager$$Lambda$6897/888509047.get(Unknown Source)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[05Sep2022 11:34:22.639] [Downloader 1/INFO] [STDERR/]: [gg.moonflower.pollen.core.client.profile.ProfileManager:lambda$getProfile$0:37]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jacksonhardaway** [comment]
Fixed
