### ISSUE TITLE
weird Error in client log

### ISSUE THREAD

**Issue by Skeithh** [MoonflowerTeam/pollen#66]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Happens at random, doesn't cause any issues (that i can take not of at least) but occasionally spams the log with the error listed.

using fabric 0.14.9 for minecraft 1.18.2.
Trying to currently phase out *any* causes for certain bugs on the server so i'm cleansweeping any errors I can.

Can't copy paste the text from the latest log because its too large apparently so I hope this suffices as its the only pollen-related error I can spot.
```

### latest.log

```shell
[00:01:32] [Downloader 12/ERROR]: Failed to retrieve entitlements for acbb6b4b-58a3-4da2-9d1c-ecb7f81c587b
java.util.concurrent.CompletionException: java.net.UnknownHostException: No such host is known (accounts.moonflower.gg)
	at gg.moonflower.pollen.core.client.entitlement.EntitlementManager$EntitlementData.lambda$getFuture$0(EntitlementManager.java:210) ~[pollen-fabric-1.4.9+1.18.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.UnknownHostException: No such host is known (accounts.moonflower.gg)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar:?]
	at gg.moonflower.pollen.core.client.profile.ProfileConnection.lambda$new$1(ProfileConnection.java:80) ~[pollen-fabric-1.4.9+1.18.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 3 more
```

**Comment by jacksonhardaway** [comment]
This shouldn't cause any issues, we're working on our backend cosmetic system atm so it's offline.
