### ISSUE TITLE
Error from Pollen right before the world hangs.

### ISSUE THREAD

**Issue by Reshy** [MoonflowerTeam/pollen#67]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
World hangs after receiving an error from Pollen in the logs, not sure the specific causes.
```

### latest.log

```shell
[21Sep2022 00:41:08.914] [Downloader 4/ERROR] [gg.moonflower.pollen.core.client.entitlement.EntitlementManager/]: Failed to retrieve entitlements for f88d39c3-3499-4aa8-bdb4-2ceaa95cee0e
java.util.concurrent.CompletionException: java.net.UnknownHostException: No such host is known (accounts.moonflower.gg)
	at gg.moonflower.pollen.core.client.entitlement.EntitlementManager$EntitlementData.lambda$getFuture$0(EntitlementManager.java:210) ~[pollen-forge-1.5.0+1.18.2.jar%23264!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.UnknownHostException: No such host is known (accounts.moonflower.gg)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar%2338!/:4.5.13]
	at gg.moonflower.pollen.core.client.profile.ProfileConnection.lambda$new$1(ProfileConnection.java:80) ~[pollen-forge-1.5.0+1.18.2.jar%23264!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 3 more
```

**Comment by jacksonhardaway** [comment]
Fixed
