### ISSUE TITLE
Lightfall

### ISSUE THREAD

**Issue by SulfuricM** [MoonflowerTeam/pollen#73]
### What version are you seeing the problem on?

1.16.5

### Describe the issue

```markdown
https://github.com/ArclightPowered/lightfall
```

### latest.log

```shell
[16:06:06 INFO]: [SulfuricM|/223.74.237.85:15751] <-> ServerConnector [mohist] has connected
[16:06:08 WARN]: [/223.74.237.85:15751|SulfuricM] <-> DownstreamBridge <-> [mohist] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument pollen:enum
[16:06:08 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument pollen:enum
[16:06:08 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[16:06:08 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[16:06:08 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[16:06:08 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[16:06:08 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[16:06:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[16:06:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[16:06:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16:06:08 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[16:06:08 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[16:06:08 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[16:06:08 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:06:08 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:06:08 ERROR]:       at java.base/java.lang.Thread.run(Unknown Source)
[16:06:08 ERROR]: Caused by: java.lang.IllegalArgumentException: No provider for argument pollen:enum
[16:06:08 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[16:06:08 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:789)
[16:06:08 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307)
[16:06:08 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84)
[16:06:08 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[16:06:08 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[16:06:08 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[16:06:08 ERROR]:       ... 20 more
[16:06:08 INFO]: [SulfuricM] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[16:06:08 INFO]: [/223.74.237.85:15751|SulfuricM] -> UpstreamBridge has disconnected
[16:06:08 INFO]: [/223.74.237.85:15751|SulfuricM] <-> DownstreamBridge <-> [mohist] has disconnected
```

**Comment by jacksonhardaway** [comment]
We do not support Bukkit/Forge hybrids, they don't work.
