### ISSUE TITLE
Description: Mod loading error has occurred

### ISSUE THREAD

**Issue by TishinaVC** [MoonflowerTeam/pollen#74]
### What version are you seeing the problem on?

1.16.5

### Describe the issue

```markdown
Boot game with listed mods installed in 1.18.2 on latest forge

https://pastebin.com/iRf1q2YT Crash report with CraftITrace included
```

### latest.log

```shell
[10:59:10] [Worker-ResourceReload-4/ERROR]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3003/0x0000000080abc438@4e1a8e3c
		2: net.minecraftforge.eventbus.EventBus$$Lambda$3003/0x0000000080abc438@52ed8575
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy99.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1053)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1039)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.api.registry.EventRegistry.lambda$createLoop$1(EventRegistry.java:38)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.core.event.PollinatedEventImpl.<init>(PollinatedEventImpl.java:31)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.api.registry.EventRegistry.create(EventRegistry.java:33)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.api.registry.EventRegistry.createLoop(EventRegistry.java:38)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.api.event.events.lifecycle.ServerLifecycleEvents.<clinit>(ServerLifecycleEvents.java:21)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.core.Pollen.onCommonPost(Pollen.java:110)
	at TRANSFORMER/pollen@1.6.1/gg.moonflower.pollen.api.platform.forge.ForgePlatform.lambda$setup$0(ForgePlatform.java:47)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.2.2/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.2/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:3298)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.GameRules.<init>(GameRules.java:120)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:183)
	... 30 more

[10:59:10] [Worker-ResourceReload-4/ERROR]: Caught exception during event FMLCommonSetupEvent dispatch for modid pollen
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at jdk.proxy3.$Proxy99.<clinit>(Unknown Source) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1053) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1039) ~[?:?]
	at gg.moonflower.pollen.api.registry.EventRegistry.lambda$createLoop$1(EventRegistry.java:38) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at gg.moonflower.pollen.core.event.PollinatedEventImpl.<init>(PollinatedEventImpl.java:31) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at gg.moonflower.pollen.api.registry.EventRegistry.create(EventRegistry.java:33) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at gg.moonflower.pollen.api.registry.EventRegistry.createLoop(EventRegistry.java:38) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at gg.moonflower.pollen.api.event.events.lifecycle.ServerLifecycleEvents.<clinit>(ServerLifecycleEvents.java:21) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at gg.moonflower.pollen.core.Pollen.onCommonPost(Pollen.java:110) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at gg.moonflower.pollen.api.platform.forge.ForgePlatform.lambda$setup$0(ForgePlatform.java:47) ~[pollen-forge-1.6.1+1.18.2.jar%23388!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.2.jar%23495!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.2.jar%23494!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:3298) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.level.GameRules.<init>(GameRules.java:120) ~[client-1.18.2-
20220404.173914-srg.jar%23493!/:?]
	at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:183) ~[client-1.18.2-20220404.173914-srg.jar%23493!/:?]
	... 30 more
[10:59:10] [Worker-ResourceReload-7/INFO]: PneumaticCraft: Repressurized is loading!
[10:59:10] [Worker-ResourceReload-7/INFO]: Making item: air_canister compatible with Holding enchantment.
[10:59:10] [Worker-ResourceReload-7/INFO]: Making item: reinforced_air_canister compatible with Holding enchantment. ect...
```

**Comment by Ocelot5836** [comment]
1.16 is EOL and this no longer happens on 1.18+
